experiment_name: monki-see-monki-sleep # This is done so that we can always find models and their corresponding datasets

data:
  train_val_test_splits: [0.6,0.2,0.2]
  max_seq_length: 65 # Max review string length for the Tokenizer
  used_datasets: { # Which dataset do we want to join and load (I can't see a case where these are not the same)
                  "Books": 0,
                  "Electronics": 0,
                  "Movies_and_TV": 0,
                  "CDs_and_Vinyl": 0,
                  "Clothing_Shoes_and_Jewelry": 0,
                  "Home_and_Kitchen": 0,
                  "Kindle_Store": 0,
                  "Sports_and_Outdoors": 0,
                  "Cell_Phones_and_Accessories": 0,
                  "Health_and_Personal_Care": 0,
                  "Toys_and_Games": 0,
                  "Video_Games": 0,
                  "Tools_and_Home_Improvement": 0,
                  "Beauty": 0,
                  "Apps_for_Android": 0,
                  "Office_Products": 0,
                  "Pet_Supplies": 0,
                  "Automotive": 0,
                  "Grocery_and_Gourmet_Food": 0,
                  "Patio_Lawn_and_Garden": 0,
                  "Baby": 1,
                  "Digital_Music": 1,
                  "Musical_Instruments": 1,
                  "Amazon_Instant_Video": 0
                  }

seed: 7

device: 'cpu' # one of 'cpu'/'gpu'

training:
  batch_size: 64     # Batch size
  lr: 0.02           # Learning rate
  max_epochs: 3
  full: false        # Whether we train the whole BART architecture or only our outer layers
  num_workers: 16

prediction:

compute:
    cloud: false # if cloud is false, all the rest is ignored. If clous is true is provided, they are used.
    subscription_id: "<your-subscription-id>"
    resource_group: "<your-resource-group>"
    workspace_name: "<your-ws-name>"
    workspace_exists: true
    location: "northeurope" # ignored if workspace_exists is true
    compute_target: "<your-compute-name>"
    environment_name: "<your-exp-name>"
    experiment_name: "<experiment-name>"
  