experiment_name: MarcoExperiment # This is done so that we can always find models and their corresponding datasets

data:
  train_val_test_splits: [0.6,0.2,0.2]
  max_seq_length: 3 # Max review string length for the Tokenizer
  used_datasets: { # Which dataset do we want to join and load (I can't see a case where these are not the same)
                  "Books": 0,
                  "Electronics": 0,
                  "Movies_and_TV": 0,
                  "CDs_and_Vinyl": 0,
                  "Clothing_Shoes_and_Jewelry": 0,
                  "Home_and_Kitchen": 0,
                  "Kindle_Store": 0,
                  "Sports_and_Outdoors": 0,
                  "Cell_Phones_and_Accessories": 0,
                  "Health_and_Personal_Care": 0,
                  "Toys_and_Games": 0,
                  "Video_Games": 0,
                  "Tools_and_Home_Improvement": 0,
                  "Beauty": 0,
                  "Apps_for_Android": 0,
                  "Office_Products": 0,
                  "Pet_Supplies": 0,
                  "Automotive": 0,
                  "Grocery_and_Gourmet_Food": 0,
                  "Patio_Lawn_and_Garden": 0,
                  "Baby": 0,
                  "Digital_Music": 0,
                  "Musical_Instruments": 1,
                  "Amazon_Instant_Video": 1
                  }

seed: 7

gpus: 0 # Choose -1 for all available

training:
  value: false # if this is false, the following os of course not used
  batch_size: 64     # Batch size
  lr: 0.02           # Learning rate
  max_epochs: 1
  full: false        # Whether we train the whole BERT architecture or only our outer layers
  num_workers: 4

prediction:

compute:
  cloud: true # if cloud is false, all the rest is ignored. If clous is true is provided, they are used.
  subscription_id: "aa4b9a75-08b4-4169-a974-a772bd186a7a"
  resource_group: "mlops_day6"
  workspace_name: "mlops_project"
  workspace_exists: true
  location: "westeurope" # ignored if workspace_exists is true
  compute_target: "s2105271"
  environment_name: "myEnvironment"

deploy: # used only if compute['cloud']: true
  value: true # if this is false, the following is of course not used
  model_name: "MarcoExperiment"
  run_id: "OctopusExperiment_1624477567_6845258d" # very ugly solution to retrieve saved weights
  version: 0 # 0 for the latest version, else the version number
  aks_compute_name: "DeployAKS" # max 16 char
  vm_instance: "Standard_A2_v2" # do not change
  agent_count: 2 # do not change
  location: "westeurope" # do not change
  purpose: "DevTest" # do not change
  service_name: "my-service" # It must only consist of lowercase letters, numbers, or dashes, start with a letter, end with a letter or number, and be between 3 and 32 characters long

wandbkey: "0b560be30b7d9ad32a84e958a3d7c1aeb94cabeb"
